#!/usr/bin/env python3
"""
Generate paper-ready tables, plots, and text summaries from the SORA control
overhead CSV outputs.

By default the script reads the current repository root and writes artifacts to:

    analysis/control_overhead/
"""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import Iterable

import matplotlib

matplotlib.use("Agg")

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from matplotlib.lines import Line2D
from matplotlib.ticker import MaxNLocator


plt.rcParams.update({
    "font.size": 30,
    "axes.titlesize": 36,
    "axes.labelsize": 30,
    "xtick.labelsize": 30,
    "ytick.labelsize": 30,
    "legend.fontsize": 27,
})

FONT_LEGEND = 27
FONT_ANNOTATION = 27
FONT_ANNOTATION_SMALL = 24
FONT_SUBPANEL = 33


REQUIRED_FILES = {
    "slot_signaling": "control_signaling_per_slot.csv",
    "message_volume": "control_message_volume.csv",
    "controller_processing": "controller_processing_time.csv",
    "reconfiguration": "reconfiguration_latency.csv",
    "throughput_impact": "transient_throughput_impact.csv",
    "cluster1": "cluster1_total_throughput.csv",
    "cluster2": "cluster2_total_throughput.csv",
}


COLORS = {
    "a1": "#4e79a7",
    "o1": "#f28e2b",
    "e2_reports": "#59a14f",
    "e2_commands": "#e15759",
    "forwarding": "#222222",
    "non_rt": "#76b7b2",
    "near_rt": "#edc948",
    "routing": "#b07aa1",
    "critical": "#d62728",
    "trigger": "#4e79a7",
    "o1_complete": "#f28e2b",
    "report_complete": "#59a14f",
    "near_rt_complete": "#af7aa1",
    "command_complete": "#e15759",
    "update_complete": "#222222",
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Build paper-ready control-overhead artifacts from ns-3 CSV outputs."
    )
    parser.add_argument(
        "--input-dir",
        default=".",
        help="Directory containing the CSV outputs (default: current directory).",
    )
    parser.add_argument(
        "--output-dir",
        default="analysis/control_overhead",
        help="Directory where the generated artifacts will be written.",
    )
    parser.add_argument(
        "--throughput-window",
        type=float,
        default=1.5,
        help="Seconds to show before/after the trigger in the throughput impact plot.",
    )
    return parser.parse_args()


def ensure_inputs(input_dir: Path) -> dict[str, pd.DataFrame]:
    dataframes: dict[str, pd.DataFrame] = {}
    missing: list[str] = []

    for key, filename in REQUIRED_FILES.items():
        path = input_dir / filename
        if not path.exists():
            missing.append(filename)
            continue
        dataframes[key] = pd.read_csv(path)

    if missing:
        raise FileNotFoundError(
            "Missing required input files: " + ", ".join(sorted(missing))
        )

    return dataframes


def latex_escape(value: object) -> str:
    text = str(value)
    replacements = {
        "\\": r"\textbackslash{}",
        "&": r"\&",
        "%": r"\%",
        "$": r"\$",
        "#": r"\#",
        "_": r"\_",
        "{": r"\{",
        "}": r"\}",
        "~": r"\textasciitilde{}",
        "^": r"\textasciicircum{}",
    }
    for old, new in replacements.items():
        text = text.replace(old, new)
    return text


def stringify_value(value: object) -> str:
    if pd.isna(value):
        return ""
    if isinstance(value, (np.integer, int)):
        return str(int(value))
    if isinstance(value, (np.floating, float)):
        if abs(value - round(value)) < 1e-9:
            return str(int(round(value)))
        return f"{float(value):.3f}".rstrip("0").rstrip(".")
    return str(value)


def write_latex_table(df: pd.DataFrame, path: Path, caption: str, label: str) -> None:
    columns = list(df.columns)
    align = "l" + "r" * (len(columns) - 1)

    with path.open("w", encoding="utf-8") as handle:
        handle.write("% Auto-generated by scripts/analyze_control_overhead.py\n")
        handle.write("\\begin{table}[t]\n")
        handle.write("\\centering\n")
        handle.write(f"\\caption{{{latex_escape(caption)}}}\n")
        handle.write(f"\\label{{{latex_escape(label)}}}\n")
        handle.write(f"\\begin{{tabular}}{{{align}}}\n")
        handle.write("\\hline\n")
        handle.write(" & ".join(latex_escape(col) for col in columns) + " \\\\\n")
        handle.write("\\hline\n")
        for _, row in df.iterrows():
            cells = [latex_escape(stringify_value(row[col])) for col in columns]
            handle.write(" & ".join(cells) + " \\\\\n")
        handle.write("\\hline\n")
        handle.write("\\end{tabular}\n")
        handle.write("\\end{table}\n")


def save_dataframe(df: pd.DataFrame, csv_path: Path, tex_path: Path, caption: str, label: str) -> None:
    df.to_csv(csv_path, index=False)
    write_latex_table(df, tex_path, caption=caption, label=label)


def save_figure(fig: plt.Figure, output_dir: Path, stem: str) -> None:
    fig.savefig(output_dir / f"{stem}.png", dpi=300, bbox_inches="tight")
    fig.savefig(output_dir / f"{stem}.pdf", bbox_inches="tight")
    plt.close(fig)


def build_slot_overhead_table(slot_df: pd.DataFrame) -> pd.DataFrame:
    table = slot_df.copy()
    table["total_messages"] = (
        table["a1_messages"]
        + table["o1_messages"]
        + table["e2_reports"]
        + table["e2_commands"]
    )
    table["reconfiguration_slot"] = table["topology_changed"].map({0: "No", 1: "Yes"})
    table = table.rename(
        columns={
            "slot_index": "Slot",
            "slot_start_s": "Start (s)",
            "reconfiguration_slot": "Topology change",
            "a1_messages": "A1 msgs",
            "o1_messages": "O1 msgs",
            "e2_reports": "E2 reports",
            "e2_commands": "E2 cmds",
            "total_messages": "Total msgs",
            "total_control_serialized_bytes": "Payload bytes",
            "forwarding_updates": "Fwd updates",
            "controller_critical_path_ms": "Critical path (ms)",
        }
    )
    keep = [
        "Slot",
        "Start (s)",
        "Topology change",
        "A1 msgs",
        "O1 msgs",
        "E2 reports",
        "E2 cmds",
        "Total msgs",
        "Payload bytes",
        "Fwd updates",
        "Critical path (ms)",
    ]
    return table[keep]


def build_message_breakdown_table(message_df: pd.DataFrame) -> pd.DataFrame:
    grouped = (
        message_df.groupby(["interface", "direction", "message_type"])["serialized_bytes"]
        .agg(["size", "sum", "mean", "min", "max"])
        .reset_index()
        .sort_values(["interface", "direction", "message_type"])
        .reset_index(drop=True)
    )
    grouped = grouped.rename(
        columns={
            "size": "count",
            "sum": "total_bytes",
            "mean": "avg_bytes",
            "min": "min_bytes",
            "max": "max_bytes",
        }
    )
    grouped["avg_bytes"] = grouped["avg_bytes"].round(3)
    grouped = grouped.rename(
        columns={
            "interface": "Interface",
            "direction": "Direction",
            "message_type": "Message type",
            "count": "Count",
            "total_bytes": "Total bytes",
            "avg_bytes": "Avg bytes",
            "min_bytes": "Min bytes",
            "max_bytes": "Max bytes",
        }
    )
    return grouped


def build_controller_stage_table(processing_df: pd.DataFrame, slot_df: pd.DataFrame) -> pd.DataFrame:
    grouped = (
        processing_df.groupby(["slot_index", "stage"], as_index=False)["duration_ms"]
        .sum()
        .pivot(index="slot_index", columns="stage", values="duration_ms")
        .fillna(0.0)
        .reset_index()
    )
    for stage in ["non_rt_orchestration", "near_rt_orchestration", "routing_xapp"]:
        if stage not in grouped.columns:
            grouped[stage] = 0.0

    grouped = grouped.merge(
        slot_df[["slot_index", "controller_critical_path_ms"]],
        on="slot_index",
        how="left",
    )
    grouped = grouped.rename(
        columns={
            "slot_index": "Slot",
            "non_rt_orchestration": "Non-RT total (ms)",
            "near_rt_orchestration": "Near-RT total (ms)",
            "routing_xapp": "Routing total (ms)",
            "controller_critical_path_ms": "Critical path (ms)",
        }
    )
    return grouped[
        [
            "Slot",
            "Non-RT total (ms)",
            "Near-RT total (ms)",
            "Routing total (ms)",
            "Critical path (ms)",
        ]
    ]


def build_reconfiguration_table(
    reconfig_df: pd.DataFrame, impact_df: pd.DataFrame, slot_df: pd.DataFrame
) -> pd.DataFrame:
    merged = reconfig_df.merge(impact_df, on="event_id", how="left")
    merged = merged.merge(
        slot_df[
            [
                "slot_index",
                "a1_messages",
                "o1_messages",
                "e2_reports",
                "e2_commands",
                "total_control_serialized_bytes",
                "forwarding_updates",
                "controller_critical_path_ms",
            ]
        ],
        on="slot_index",
        how="left",
    )

    merged["o1_stage_ms"] = (
        (merged["o1_completion_time_s"] - merged["trigger_time_s"]) * 1000.0
    )
    merged["report_collection_ms"] = (
        (merged["e2_report_completion_time_s"] - merged["o1_completion_time_s"]) * 1000.0
    )
    merged["near_rt_and_routing_ms"] = (
        (merged["near_rt_processing_completion_time_s"] - merged["e2_report_completion_time_s"])
        * 1000.0
    )
    merged["command_dispatch_ms"] = (
        (merged["e2_command_dispatch_time_s"] - merged["near_rt_processing_completion_time_s"])
        * 1000.0
    )
    merged["command_apply_ms"] = (
        (merged["forwarding_update_completion_time_s"] - merged["e2_command_dispatch_time_s"])
        * 1000.0
    )
    merged["control_messages"] = (
        merged["a1_messages"]
        + merged["o1_messages"]
        + merged["e2_reports"]
        + merged["e2_commands"]
    )

    table = merged.rename(
        columns={
            "event_id": "Event",
            "slot_index": "Slot",
            "trigger_time_s": "Trigger (s)",
            "control_messages": "Ctrl msgs",
            "total_control_serialized_bytes": "Payload bytes",
            "reconfiguration_latency_ms": "Latency (ms)",
            "o1_stage_ms": "O1 stage (ms)",
            "report_collection_ms": "Report stage (ms)",
            "near_rt_and_routing_ms": "Near-RT+routing (ms)",
            "command_dispatch_ms": "Cmd dispatch (ms)",
            "command_apply_ms": "Apply stage (ms)",
            "forwarding_updates": "Fwd updates",
            "controller_critical_path_ms": "Critical path (ms)",
            "baseline_total_mbps": "Baseline (Mbps)",
            "min_total_mbps": "Min (Mbps)",
            "throughput_drop_pct": "Drop (%)",
            "recovery_latency_ms": "Recovery (ms)",
        }
    )
    keep = [
        "Event",
        "Slot",
        "Trigger (s)",
        "Ctrl msgs",
        "Payload bytes",
        "Latency (ms)",
        "O1 stage (ms)",
        "Report stage (ms)",
        "Near-RT+routing (ms)",
        "Cmd dispatch (ms)",
        "Apply stage (ms)",
        "Fwd updates",
        "Critical path (ms)",
        "Baseline (Mbps)",
        "Min (Mbps)",
        "Drop (%)",
        "Recovery (ms)",
    ]
    table = table[keep].copy()
    for column in [
        "Trigger (s)",
        "Latency (ms)",
        "O1 stage (ms)",
        "Report stage (ms)",
        "Near-RT+routing (ms)",
        "Cmd dispatch (ms)",
        "Apply stage (ms)",
        "Critical path (ms)",
        "Baseline (Mbps)",
        "Min (Mbps)",
        "Drop (%)",
        "Recovery (ms)",
    ]:
        table[column] = table[column].round(3)
    return table


def highlight_reconfiguration_slots(ax: plt.Axes, slot_df: pd.DataFrame) -> None:
    for slot in slot_df.loc[slot_df["topology_changed"] == 1, "slot_index"]:
        ax.axvspan(slot - 0.5, slot + 0.5, color="#ffe7b3", alpha=0.14, zorder=0)


def plot_control_overhead(slot_df: pd.DataFrame, output_dir: Path) -> None:
    fig, axes = plt.subplots(2, 1, figsize=(13.5, 10.5), sharex=True)
    fig.subplots_adjust(top=0.92, bottom=0.10, hspace=0.42)
    ax_counts, ax_bytes = axes

    x = slot_df["slot_index"].values
    width = 0.65

    highlight_reconfiguration_slots(ax_counts, slot_df)
    highlight_reconfiguration_slots(ax_bytes, slot_df)

    count_series = [
        ("o1_messages", "O1 msgs", COLORS["o1"]),
        ("e2_commands", "E2 cmds", COLORS["e2_commands"]),
    ]
    count_bottom = np.zeros(len(slot_df))
    for column, label, color in count_series:
        ax_counts.bar(x, slot_df[column], width, bottom=count_bottom, label=label, color=color)
        count_bottom += slot_df[column].values
    ax_counts.plot(
        x,
        slot_df["forwarding_updates"],
        color=COLORS["forwarding"],
        marker="o",
        linestyle="--",
        linewidth=1.8,
        label="Fwd updates",
    )
    ax_counts.set_ylabel("Control events / slot")
    ax_counts.set_xlabel("Control slot index", labelpad=-2)
    ax_counts.tick_params(axis="x", labelbottom=True)
    ax_counts.xaxis.set_major_locator(MaxNLocator(integer=True))

    byte_series = [
        ("a1_serialized_bytes", "A1 bytes", COLORS["a1"]),
        ("o1_serialized_bytes", "O1 bytes", COLORS["o1"]),
        ("e2_report_serialized_bytes", "E2 report bytes", COLORS["e2_reports"]),
        ("e2_command_serialized_bytes", "E2 cmd bytes", COLORS["e2_commands"]),
    ]
    byte_bottom = np.zeros(len(slot_df))
    for column, label, color in byte_series:
        ax_bytes.bar(x, slot_df[column], width, bottom=byte_bottom, label=label, color=color)
        byte_bottom += slot_df[column].values

    total_bytes = slot_df["total_control_serialized_bytes"].values
    ax_bytes.set_ylim(0, max(total_bytes) * 1.22)
    for x_value, total in zip(x, total_bytes):
        ax_bytes.text(
            x_value,
            total + max(total_bytes) * 0.025,
            f"{int(total)}",
            ha="center",
            va="bottom",
            fontsize=FONT_ANNOTATION,
        )

    # ax_bytes.set_ylabel("Serialized control-plane volume (bytes)")
    ax_bytes.set_ylabel("Control msg volume (bytes)")
    ax_bytes.set_xlabel("Control slot index", labelpad=-2)
    ax_bytes.xaxis.set_major_locator(MaxNLocator(integer=True))

    combined_handles = [
        Line2D(
            [0],
            [0],
            color=COLORS["forwarding"],
            marker="o",
            linestyle="--",
            linewidth=1.8,
            label="Fwd updates",
        ),
        plt.Rectangle((0, 0), 1, 1, color=COLORS["o1"], label="O1 msgs"),
        plt.Rectangle((0, 0), 1, 1, color=COLORS["e2_commands"], label="E2 cmds"),
        plt.Rectangle((0, 0), 1, 1, color=COLORS["a1"], label="A1"),
        plt.Rectangle((0, 0), 1, 1, color=COLORS["e2_reports"], label="E2 report"),
    ]
    fig.legend(
        handles=combined_handles,
        loc="upper center",
        bbox_to_anchor=(0.5, 1.05),
        ncol=5,
        fontsize=FONT_LEGEND - 4,
        frameon=True,
        borderaxespad=0.2,
        columnspacing=0.5,
        handlelength=1.4,
        handletextpad=0.4,
    )

    ax_counts.text(0.5, -0.26, "(a)", transform=ax_counts.transAxes, ha="center", va="top", fontsize=FONT_SUBPANEL)
    ax_bytes.text(0.5, -0.26, "(b)", transform=ax_bytes.transAxes, ha="center", va="top", fontsize=FONT_SUBPANEL)

    save_figure(fig, output_dir, "control_overhead_per_slot")


def plot_controller_processing(stage_df: pd.DataFrame, output_dir: Path, reconfig_slots: Iterable[int]) -> None:
    fig, ax = plt.subplots(figsize=(13.5, 7.2), constrained_layout=True)
    x = stage_df["Slot"].values
    width = 0.65

    for slot in reconfig_slots:
        ax.axvspan(slot - 0.5, slot + 0.5, color="#ffe7b3", alpha=0.35, zorder=0)

    bottoms = np.zeros(len(stage_df))
    series = [
        ("Non-RT total (ms)", "Non-RT total", COLORS["non_rt"]),
        ("Near-RT total (ms)", "Near-RT total", COLORS["near_rt"]),
        ("Routing total (ms)", "Routing total", COLORS["routing"]),
    ]
    for column, label, color in series:
        ax.bar(x, stage_df[column], width, bottom=bottoms, label=label, color=color)
        bottoms += stage_df[column].values

    ax.plot(
        x,
        stage_df["Critical path (ms)"],
        color=COLORS["critical"],
        marker="o",
        linestyle="--",
        linewidth=2.0,
        label="Critical path",
    )
    ax.set_title("Controller-side processing time per slot")
    ax.set_xlabel("Control slot index")
    ax.set_ylabel("Time (ms)")
    ax.xaxis.set_major_locator(MaxNLocator(integer=True))
    ax.legend(loc="upper center", bbox_to_anchor=(0.5, 0.99), ncol=4, fontsize=FONT_LEGEND)

    save_figure(fig, output_dir, "controller_processing_breakdown")


def plot_reconfiguration_timeline(reconfig_df: pd.DataFrame, output_dir: Path) -> None:
    if reconfig_df.empty:
        return

    fig, ax = plt.subplots(figsize=(18, max(7.0, 4.5 + 1.8 * len(reconfig_df))), constrained_layout=True)

    legend_handles = [
        Line2D([0], [0], marker="o", color="w", markerfacecolor=COLORS["trigger"], label="Trigger", markersize=8),
        Line2D([0], [0], marker="o", color="w", markerfacecolor=COLORS["o1_complete"], label="O1 complete", markersize=8),
        Line2D([0], [0], marker="o", color="w", markerfacecolor=COLORS["report_complete"], label="E2 reports complete", markersize=8),
        Line2D([0], [0], marker="o", color="w", markerfacecolor=COLORS["near_rt_complete"], label="Near-RT+routing complete", markersize=8),
        Line2D([0], [0], marker="o", color="w", markerfacecolor=COLORS["command_complete"], label="E2 cmds dispatched", markersize=8),
        Line2D([0], [0], marker="o", color="w", markerfacecolor=COLORS["update_complete"], label="Forwarding updated", markersize=8),
    ]
    annotation_offsets = {
        "Trigger": (0, 14, "center"),
        "O1 complete": (0, 14, "center"),
        "E2 reports complete": (-12, -50, "center"),
        "Near-RT+routing complete": (-22, 34, "right"),
        "E2 cmds dispatched": (22, 10, "left"),
        "Forwarding updated": (12, 34, "left"),
    }

    for row_index, row in enumerate(reconfig_df.itertuples(index=False)):
        y = len(reconfig_df) - 1 - row_index
        stage_points = {
            "Trigger": 0.0,
            "O1 complete": (row.o1_completion_time_s - row.trigger_time_s) * 1000.0,
            "E2 reports complete": (row.e2_report_completion_time_s - row.trigger_time_s) * 1000.0,
            "Near-RT+routing complete": (row.near_rt_processing_completion_time_s - row.trigger_time_s) * 1000.0,
            "E2 cmds dispatched": (row.e2_command_dispatch_time_s - row.trigger_time_s) * 1000.0,
            "Forwarding updated": (row.forwarding_update_completion_time_s - row.trigger_time_s) * 1000.0,
        }
        colors = {
            "Trigger": COLORS["trigger"],
            "O1 complete": COLORS["o1_complete"],
            "E2 reports complete": COLORS["report_complete"],
            "Near-RT+routing complete": COLORS["near_rt_complete"],
            "E2 cmds dispatched": COLORS["command_complete"],
            "Forwarding updated": COLORS["update_complete"],
        }

        ax.hlines(y, 0.0, stage_points["Forwarding updated"], color="#999999", linewidth=2.5)
        for label, x_value in stage_points.items():
            ax.scatter(x_value, y, s=70, color=colors[label], zorder=3)
            dx, dy, ha = annotation_offsets[label]
            ax.annotate(
                f"{label}\n{x_value:.1f} ms",
                (x_value, y),
                textcoords="offset points",
                xytext=(dx, dy),
                ha=ha,
                fontsize=FONT_ANNOTATION_SMALL,
            )

    ax.set_yticks(list(range(len(reconfig_df))))
    ax.set_yticklabels(
        [f"Event {int(row.event_id)} (slot {int(row.slot_index)})" for row in reconfig_df.itertuples(index=False)][::-1]
    )
    ax.set_xlabel("Time from reconfiguration trigger (ms)")
    ax.set_title("Reconfiguration timeline")
    ax.grid(True, axis="x", alpha=0.3)
    ax.legend(handles=legend_handles, loc="upper center", bbox_to_anchor=(0.5, 0.98), ncol=2, fontsize=FONT_LEGEND)

    save_figure(fig, output_dir, "reconfiguration_timeline")


def plot_transient_throughput(
    cluster1_df: pd.DataFrame,
    cluster2_df: pd.DataFrame,
    impact_df: pd.DataFrame,
    reconfig_df: pd.DataFrame,
    output_dir: Path,
    window: float,
) -> None:
    merged = cluster1_df.rename(columns={"throughput_mbps": "cluster1_mbps"}).merge(
        cluster2_df.rename(columns={"throughput_mbps": "cluster2_mbps"}),
        on="time",
        how="outer",
    )
    merged = merged.sort_values("time").fillna(0.0)
    merged["total_mbps"] = merged["cluster1_mbps"] + merged["cluster2_mbps"]

    if not reconfig_df.empty:
        trigger_time = float(reconfig_df["trigger_time_s"].iloc[0])
    else:
        trigger_time = float(merged["time"].median())

    baseline = float(impact_df["baseline_total_mbps"].iloc[0])
    min_time = float(impact_df["min_time_s"].iloc[0])
    recovery_time = float(impact_df["recovery_time_s"].iloc[0])
    min_total = float(impact_df["min_total_mbps"].iloc[0])

    right_edge = max(trigger_time + window, recovery_time + 0.2)
    plot_df = merged[(merged["time"] >= trigger_time - window) & (merged["time"] <= right_edge)]

    fig, ax = plt.subplots(figsize=(14, 7), constrained_layout=True)
    total_handle = ax.plot(
        plot_df["time"],
        plot_df["total_mbps"],
        color="#1f77b4",
        linewidth=2.2,
        label="Total throughput",
    )[0]
    baseline_handle = ax.axhline(
        baseline,
        color="#666666",
        linestyle="--",
        linewidth=1.5,
        label="Baseline",
    )
    trigger_handle = ax.axvline(
        trigger_time,
        color=COLORS["trigger"],
        linestyle="--",
        linewidth=1.5,
        label="Trigger",
    )
    minimum_handle = ax.axvline(
        min_time,
        color=COLORS["command_complete"],
        linestyle=":",
        linewidth=1.5,
        label="Minimum",
    )
    recovery_handle = ax.axvline(
        recovery_time,
        color=COLORS["e2_reports"],
        linestyle="-.",
        linewidth=1.5,
        label="Recovery",
    )
    ax.axvspan(trigger_time, recovery_time, color="#ffe7b3", alpha=0.25)
    ax.scatter([min_time], [min_total], color=COLORS["command_complete"], s=65, zorder=3)
    ax.annotate(
        f"Min {min_total:.2f} Mbps\nDrop {float(impact_df['throughput_drop_pct'].iloc[0]):.2f}%",
        (min_time, min_total),
        textcoords="offset points",
        xytext=(10, -10),
        fontsize=FONT_ANNOTATION,
    )
    ax.annotate(
        f"Recovered in {float(impact_df['recovery_latency_ms'].iloc[0]):.0f} ms",
        (recovery_time, baseline),
        textcoords="offset points",
        xytext=(8, 14),
        fontsize=FONT_ANNOTATION,
    )
    # ax.set_title("Transient throughput impact during reconfiguration")
    ax.set_xlabel("Time (s)")
    ax.set_ylabel("Total throughput to CU (Mbps)")
    legend_handles = [
        total_handle,
        trigger_handle,
        baseline_handle,
        minimum_handle,
        recovery_handle,
    ]
    legend_labels = [handle.get_label() for handle in legend_handles]
    ax.legend(
        legend_handles,
        legend_labels,
        loc="center right",
        bbox_to_anchor=(0.985, 0.55),
        ncol=1,
        fontsize=FONT_LEGEND,
        frameon=True,
        handlelength=2.0,
        columnspacing=1.0,
    )
    ax.grid(True, alpha=0.25)

    save_figure(fig, output_dir, "transient_throughput_impact")


def build_numbers_summary(
    slot_df: pd.DataFrame,
    reconfig_df: pd.DataFrame,
    impact_df: pd.DataFrame,
    message_breakdown_df: pd.DataFrame,
) -> dict[str, float | int | str]:
    reconfig_slot = slot_df.loc[slot_df["topology_changed"] == 1].iloc[0]
    reconfig_event = reconfig_df.iloc[0]
    impact = impact_df.iloc[0]

    e2_report_avg = float(
        message_breakdown_df.loc[
            (message_breakdown_df["Interface"] == "E2")
            & (message_breakdown_df["Direction"] == "uplink"),
            "Avg bytes",
        ].mean()
    )
    e2_command_avg = float(
        message_breakdown_df.loc[
            (message_breakdown_df["Interface"] == "E2")
            & (message_breakdown_df["Direction"] == "downlink"),
            "Avg bytes",
        ].mean()
    )
    a1_avg = float(
        message_breakdown_df.loc[
            (message_breakdown_df["Interface"] == "A1"),
            "Avg bytes",
        ].mean()
    )
    o1_avg = float(
        message_breakdown_df.loc[
            (message_breakdown_df["Interface"] == "O1"),
            "Avg bytes",
        ].mean()
    )

    return {
        "reconfiguration_slot": int(reconfig_slot["slot_index"]),
        "reconfiguration_slot_start_s": float(reconfig_slot["slot_start_s"]),
        "a1_messages": int(reconfig_slot["a1_messages"]),
        "o1_messages": int(reconfig_slot["o1_messages"]),
        "e2_reports": int(reconfig_slot["e2_reports"]),
        "e2_commands": int(reconfig_slot["e2_commands"]),
        "forwarding_updates": int(reconfig_slot["forwarding_updates"]),
        "payload_bytes": int(reconfig_slot["total_control_serialized_bytes"]),
        "controller_critical_path_ms": float(reconfig_slot["controller_critical_path_ms"]),
        "reconfiguration_latency_ms": float(reconfig_event["reconfiguration_latency_ms"]),
        "baseline_total_mbps": float(impact["baseline_total_mbps"]),
        "min_total_mbps": float(impact["min_total_mbps"]),
        "throughput_drop_pct": float(impact["throughput_drop_pct"]),
        "recovery_latency_ms": float(impact["recovery_latency_ms"]),
        "a1_avg_bytes": a1_avg,
        "o1_avg_bytes": o1_avg,
        "e2_report_avg_bytes": e2_report_avg,
        "e2_command_avg_bytes": e2_command_avg,
    }


def write_paper_summary(numbers: dict[str, float | int | str], output_path: Path) -> None:
    total_messages = (
        int(numbers["a1_messages"])
        + int(numbers["o1_messages"])
        + int(numbers["e2_reports"])
        + int(numbers["e2_commands"])
    )
    summary = f"""Auto-generated control-overhead summary
=====================================

Reconfiguration occurs in slot {int(numbers["reconfiguration_slot"])} at t={float(numbers["reconfiguration_slot_start_s"]):.1f} s.

Suggested paper-ready statements:

1. During the reconfiguration slot, the prototype executes {total_messages} control signaling events, including
   {int(numbers["a1_messages"])} A1 updates, {int(numbers["o1_messages"])} O1 updates,
   {int(numbers["e2_reports"])} E2 reports, and {int(numbers["e2_commands"])} E2 commands.

2. The reconfiguration slot carries {int(numbers["payload_bytes"])} bytes of serialized control payload and
   results in {int(numbers["forwarding_updates"])} forwarding-table updates.

3. The end-to-end reconfiguration latency is {float(numbers["reconfiguration_latency_ms"]):.1f} ms, while the
   controller critical path is {float(numbers["controller_critical_path_ms"]):.1f} ms.

4. Aggregate throughput drops from {float(numbers["baseline_total_mbps"]):.4f} Mbps to
   {float(numbers["min_total_mbps"]):.5f} Mbps during reconfiguration, corresponding to a
   {float(numbers["throughput_drop_pct"]):.2f}% temporary degradation, and recovers within
   {float(numbers["recovery_latency_ms"]):.0f} ms.

5. Average serialized payload sizes are approximately {float(numbers["a1_avg_bytes"]):.1f} bytes for A1 policy updates,
   {float(numbers["o1_avg_bytes"]):.1f} bytes for O1 reassignment updates,
   {float(numbers["e2_report_avg_bytes"]):.1f} bytes for E2 reports, and
   {float(numbers["e2_command_avg_bytes"]):.1f} bytes for E2 commands.
"""
    output_path.write_text(summary, encoding="utf-8")


def main() -> None:
    args = parse_args()
    input_dir = Path(args.input_dir).resolve()
    output_dir = Path(args.output_dir).resolve()
    output_dir.mkdir(parents=True, exist_ok=True)

    dataframes = ensure_inputs(input_dir)
    slot_df = dataframes["slot_signaling"].sort_values("slot_index").reset_index(drop=True)
    message_df = dataframes["message_volume"].copy()
    processing_df = dataframes["controller_processing"].copy()
    reconfig_df = dataframes["reconfiguration"].copy()
    impact_df = dataframes["throughput_impact"].copy()
    cluster1_df = dataframes["cluster1"].copy()
    cluster2_df = dataframes["cluster2"].copy()

    slot_table = build_slot_overhead_table(slot_df)
    message_breakdown_table = build_message_breakdown_table(message_df)
    controller_stage_table = build_controller_stage_table(processing_df, slot_df)
    reconfiguration_table = build_reconfiguration_table(reconfig_df, impact_df, slot_df)

    save_dataframe(
        slot_table,
        output_dir / "slot_overhead_summary.csv",
        output_dir / "slot_overhead_summary.tex",
        caption="Per-slot control signaling and payload summary.",
        label="tab:slot_overhead_summary",
    )
    save_dataframe(
        message_breakdown_table,
        output_dir / "message_volume_breakdown.csv",
        output_dir / "message_volume_breakdown.tex",
        caption="Serialized control payload volume by interface and message type.",
        label="tab:message_volume_breakdown",
    )
    save_dataframe(
        controller_stage_table,
        output_dir / "controller_stage_breakdown.csv",
        output_dir / "controller_stage_breakdown.tex",
        caption="Controller-side processing time aggregated by slot.",
        label="tab:controller_stage_breakdown",
    )
    save_dataframe(
        reconfiguration_table,
        output_dir / "reconfiguration_summary.csv",
        output_dir / "reconfiguration_summary.tex",
        caption="Reconfiguration latency and transient throughput impact summary.",
        label="tab:reconfiguration_summary",
    )

    plot_control_overhead(slot_df, output_dir)
    plot_controller_processing(
        controller_stage_table,
        output_dir,
        reconfig_slots=slot_df.loc[slot_df["topology_changed"] == 1, "slot_index"].tolist(),
    )
    plot_reconfiguration_timeline(reconfig_df, output_dir)
    plot_transient_throughput(
        cluster1_df,
        cluster2_df,
        impact_df,
        reconfig_df,
        output_dir,
        window=args.throughput_window,
    )

    numbers = build_numbers_summary(slot_df, reconfig_df, impact_df, message_breakdown_table)
    write_paper_summary(numbers, output_dir / "paper_summary.txt")

    generated = [
        "slot_overhead_summary.csv",
        "slot_overhead_summary.tex",
        "message_volume_breakdown.csv",
        "message_volume_breakdown.tex",
        "controller_stage_breakdown.csv",
        "controller_stage_breakdown.tex",
        "reconfiguration_summary.csv",
        "reconfiguration_summary.tex",
        "control_overhead_per_slot.png",
        "control_overhead_per_slot.pdf",
        "controller_processing_breakdown.png",
        "controller_processing_breakdown.pdf",
        "reconfiguration_timeline.png",
        "reconfiguration_timeline.pdf",
        "transient_throughput_impact.png",
        "transient_throughput_impact.pdf",
        "paper_summary.txt",
    ]

    print("Generated artifacts:")
    for filename in generated:
        print(f"- {output_dir / filename}")


if __name__ == "__main__":
    main()
